# Site settings
title: JRRN Coding! | A simple Jekyll blog
description: "Blog de desarrollo .NET"
url: "https://jrrn.github.io"
author:
  name: "JRRN"
  email: ""
  url: "https://jrrn.github.io"

# Build settings
baseurl: /  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - rouge
  - jekyll-seo-tag

# Custom variables
version: "1.0.0"

# Options
reverse: false
