# Site settings
title: JRRN Coding! | A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."
url: "https://jrrn.github.io"
author:
  name: "JRRN"
  email: ""
  url: "https://jrrn.github.io"

# Build settings
baseurl: /  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Custom variables
version: "0.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
